version: '3.3'

services:

  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - ${OLLAMA_EXTERNAL_PORT}:${OLLAMA_INTERNAL_PORT}
    env_file:
      - .env
    volumes:
      - ./volumes/ollama:/root/.ollama
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #       - driver: nvidia
    #         device_ids: ['2', '3']
    #         capabilities: [gpu]

  frontend:
    build: services/frontend
    container_name: frontend
    ports:
      - ${FRONTEND_EXTERNAL_PORT}:${FRONTEND_INTERNAL_PORT}
    env_file:
      - .env
    depends_on:
      - llm_facade
      - code_analyzer
      - db_interface

  llm_facade:
    build: services/llm_facade
    container_name: llm_facade
    ports:
      - ${LLM_FACADE_EXTERNAL_PORT}:${LLM_FACADE_INTERNAL_PORT}
    depends_on:
      - ollama
      - db_interface
    env_file:
      - .env

  code_analyzer:
    build: services/code_analyzer
    container_name: code_analyzer
    ports:
      - ${CODE_ANALYZER_EXTERNAL_PORT}:${CODE_ANALYZER_INTERNAL_PORT}
    env_file:
      - .env
    depends_on:
      - db_interface

  db:
    image: postgres:12.1
    container_name: db
    ports:
      - ${DB_EXTERNAL_PORT}:${DB_INTERNAL_PORT}
    env_file:
      - .env
    volumes:
      - ./volumes/db-data:/var/lib/postgresql

  db_interface:
    build: services/db_interface
    container_name: db_interface
    ports:
      - ${DB_INTERFACE_EXTERNAL_PORT}:${DB_INTERFACE_INTERNAL_PORT}
    env_file:
      - .env
    depends_on:
      - db
